databases:
  - name: invite-only-app
    databaseName: react_rails_api_project_template_production1
    user: react_rails_api_project_template1

services:
  - type: web
    plan: free
    name: invite-only-app
    env: ruby
    repo: https://github.com/anri0806/invite-only-app
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: invite-only-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false