databases:
  - name: invite-only
    plan: free
    databaseName: invite-only
    user: invite-only

services:
  - type: web
    plan: free
    name: invite-only
    env: ruby
    repo: https://github.com/anri0806/invite-only
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: invite-only
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false